name: Daily News

on:
  schedule:
    - cron: '30 22 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 가져오기
        uses: actions/checkout@v4

      - name: Python 설치
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 라이브러리 설치
        run: pip install requests

      - name: 실행
        run: python main.py
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          NTFY_TOPIC: ${{ secrets.NTFY_TOPIC }}
